version: '3'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: nicktv-flask
    image: nicktv-flask:latest
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_PORT: 5000
      MONGODB_DATABASE: nicktvdb
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./app:/var/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    command: ["gunicorn", "--config=gunicorn.py", "wsgi"] # Reload doesn't work without this

  mongodb:
    image: mongo:4.0.8
    container_name: nicktv-mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: nicktvdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nicktv-webserver:latest
    container_name: nicktv-webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "2222:80"
      - "2223:443"
    volumes:
      - nginxdata:/var/log/nginx
      - ${MEDIA_ROOT_DIR}:/www/media
    depends_on:
      - flask
    networks:
      - frontend

  calendar:
    build:
      context: calendar
      dockerfile: Dockerfile
    container_name: nicktv-calendar
    image: nicktv-calendar:latest
    volumes:
      - ./calendar:/var/calendar
      - ${CALENDAR_SERVICE_ACCOUNT_KEY}:/secrets/calendar-service-account-key.json
    depends_on:
      - webserver
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local
